version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  helm: circleci/helm@1.2.0
  aws-cli: circleci/aws-cli@1.4.0
  aws-ecr: circleci/aws-ecr@6.15.3
  kubernetes: circleci/kubernetes@1.3.0
  #sonarcloud: sonarsource/sonarcloud@1.0.3
parameters:
  image-tag:
    type: string
    default: "latest"
  project-dir:
    type: string
    default: ./
  registry:
    type: string
    default: 836163894025.dkr.ecr.eu-central-1.amazonaws.com

commands:
  setup-aws-profiles:
    steps:
      - run:
          name: aws profiles setup
          command: |
            npx @syngenta-digital/acp --file ./aws/profiles.yml
            aws sts get-caller-identity

dev_only_filters: &dev_only_filters
  context: cropwise-spray-assist-cicd
  profile: dev

qa_only_filters: &qa_only_filters
  context: cropwise-spray-assist-cicd
  profile: qa

prod_only_filters: &prod_only_filters
  context: cropwise-spray-assist-cicd
  profile: prod

jobs:
  build-and-push-image:
    docker:
      - image: circleci/node:12.10.0
    parameters:
      profile:
        type: string
      tag:
        type: string
    steps:
      - aws-cli/setup
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - setup-aws-profiles
      - run: cat ~/.aws/credentials
      - run: cat ~/.aws/config
      - aws-ecr/build-and-push-image:
          account-url: DEV_AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          profile-name: <<parameters.profile>>
          path: .
          region: DEV_AWS_REGION
          repo: spray-assist
          tag: <<parameters.tag>>

  deploy-in-dev-eks:
    docker:
      - image: "cimg/base:stable"
    parameters:
      profile:
        type: string
        default: dev
    steps:
      - checkout
      - kubernetes/install-kubectl:
          kubectl-version: v1.23.0
      - aws-cli/setup
      - helm/install-helm-client:
          version: v3.6.1
      - run: echo -e "[profile dev]\nrole_arn = arn:aws:iam::836163894025:role/CICD\nsource_profile=default" >> ~/.aws/config
      - run: echo -e "[profile qa]\nrole_arn = arn:aws:iam::329143583580:role/CICD\nsource_profile=default" >> ~/.aws/config
      # - run: echo -e "[profile prod]\nrole_arn = arn:aws:iam::461741163030:role/CICD\nsource_profile=default" >> ~/.aws/config
      - run: aws sts get-caller-identity
      - run: aws eks --region ${DEV_AWS_REGION} update-kubeconfig --name <<parameters.profile>>-spary-assist-k8s-cluster --profile <<parameters.profile>>
      - run: cat ~/.kube/config
      - run: cat ~/.aws/config
      - run: cat ~/.aws/credentials
      - run: kubectl get nodes
      - run: helm version
      - run: printenv
      - run: ls -la
      #- run: helm install --debug --dry-run spray-assist-api ./chart
      - run: helm upgrade --install spray-assist-api ./chart -f <<pipeline.parameters.project-dir>>/chart/<<parameters.profile>>-values.yaml -n spray-assist-api  --create-namespace  --debug

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-image:
          tag: latest
          <<: *dev_only_filters
          filters:
            tags:
              only: /^dev.*/
            branches:
              ignore: /.*/

      - deploy-in-dev-eks:
          name: deploy-in-dev
          context: cropwise-spray-assist-cicd
          requires:
            - build-and-push-image
          <<: *dev_only_filters
          filters:
            tags:
              only: /^dev.*/
            branches:
              ignore: /.*/
  build-and-deploy-qa:
    jobs:
      - build-and-push-image:
          tag: latest-qa
          <<: *qa_only_filters
          filters:
            tags:
              only: /^qa.*/
            branches:
              ignore: /.*/
      - deploy-in-dev-eks:
          name: deploy-in-qa
          context: cropwise-spray-assist-cicd
          requires:
            - build-and-push-image
          <<: *qa_only_filters
          filters:
            tags:
              only: /^qa.*/ #change tag & remove comment
            branches:
              ignore: /.*/
  build-and-deploy-prod:
    jobs:
      - build-and-push-image:
          tag: latest-prod
          <<: *prod_only_filters
          filters:
            tags:
              only: /^prod.*/
            branches:
              ignore: /.*/
      - deploy-in-dev-eks:
          name: deploy-in-prod
          context: cropwise-spray-assist-cicd
          requires:
            - build-and-push-image
          <<: *prod_only_filters
          filters:
            tags:
              only: /^prod.*/
            branches:
              ignore: /.*/
