version: 2.1
orbs:
  node: circleci/node@5.0.2
executors:
  my-executor:
    docker:
      - image: circleci/node
    resource_class: medium
    working_directory: /tmp



jobs:
  build_and_test:
    executor: node/default
    working_directory: /home
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test 
          name: Run tests
      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output
  test:
    executor: node/default
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/workspace
      - run: 
          command: ls
  


workflows:
  test_my_app:
    jobs:
      - build_and_test
      - test:
          requires:
            - build_and_test

      #- deploy:
       #   requires:
        #    - build_and_test # only deploy if the build_and_test job has completed
         # filters:
          #  branches:
           #   only: main # only deploy when on main
