version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    executor: node/default
    resource_class: medium
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test &
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
jobs:
  build_docker_image:
    #executor: node/default
    #resource_class: medium
    #- persist_to_workspace:
     #     root: ~/project
      #    paths:
       #     - .
    - run: 
        command: ls


workflows:
  test_my_app:
    jobs:
      - build_and_test
      #- deploy:
       #   requires:
        #    - build_and_test # only deploy if the build_and_test job has completed
         # filters:
          #  branches:
           #   only: main # only deploy when on main
