version: 2.1



executors:
  docker-executor:
    docker:
      - image: circleci/node:latest
    environment:
      ## If prod, make sure you're enabling correct acm file
      ENV: "dev"
      PROJECT: "seed-selector"
defaults: &defaults
  executor: docker-executor
  working_directory: ~/cdframework


filters_dev: &dev_only_filters
  profile: dev

filters_qa: &qa_only_filters
  profile: qa

filters_prod: &prod_only_filters
  profile: prod


jobs:
  build-and-push-image:
    <<: *defaults 
    parameters:
      profile:
        type: string
    steps:
      - run: echo <<parameters.profile>>
   

  

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-image:
          <<: *$filters_${ENV}

    
