version: 2.1
orbs:
  node: circleci/node@5.0.2
executors:
  my-executor:
    docker:
      - image: circleci/node
    resource_class: medium
dev_only_filters: &dev_only_filters
  profile: dev
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/



jobs:
  build_and_test:
    executor: my-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test 
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  test:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run: 
          command: ls
  


workflows:
  test_my_app:
    jobs:
      - build_and_test:
        <<: *dev_only_filters
          
      #- deploy:
       #   requires:
        #    - build_and_test # only deploy if the build_and_test job has completed
         # filters:
          #  branches:
           #   only: main # only deploy when on main
